name: Backend CI/CD

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  lint-test-build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for lint/test
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd backend
          npm install

      # Step 4: Run lint (if available)
      - name: Run lint
        run: |
          cd backend
          npm run lint || echo "Lint step skipped or failed"

      # Step 5: Run tests (if available)
      - name: Run tests
        run: |
          cd backend
          npm test || echo "Tests skipped or failed"

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 7: Build backend image
      - name: Build backend image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:${{ github.sha }} \
            ./backend

      # Step 8: Push backend image
      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:${{ github.sha }}
